-- MySQL Script generated by MySQL Workbench
-- Sun Nov 29 10:53:39 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`eleve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eleve` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eleve` (
  `ideleve` INT NOT NULL,
  `nom_prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ideleve`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`professeur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`professeur` (
  `idprofesseur` INT NOT NULL,
  `nom_prenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `mot_de_passe` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idprofesseur`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`cours` ;

CREATE TABLE IF NOT EXISTS `mydb`.`cours` (
  `idcours` INT NOT NULL,
  `nom_cours` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `professeur_idprofesseur` INT NOT NULL,
  PRIMARY KEY (`idcours`, `professeur_idprofesseur`),
  CONSTRAINT `fk_cours_professeur1`
    FOREIGN KEY (`professeur_idprofesseur`)
    REFERENCES `mydb`.`professeur` (`idprofesseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_cours_professeur1_idx` ON `mydb`.`cours` (`professeur_idprofesseur` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`validite`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`validite` ;

CREATE TABLE IF NOT EXISTS `mydb`.`validite` (
  `idvalidite` INT NOT NULL,
  `est_valide` INT NOT NULL,
  PRIMARY KEY (`idvalidite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`competences` ;

CREATE TABLE IF NOT EXISTS `mydb`.`competences` (
  `idcompetences` INT NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `cours_idcours` INT NOT NULL,
  `validite_idvalidite` INT NOT NULL,
  PRIMARY KEY (`idcompetences`, `cours_idcours`, `validite_idvalidite`),
  CONSTRAINT `fk_competences_cours`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `mydb`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competences_validite1`
    FOREIGN KEY (`validite_idvalidite`)
    REFERENCES `mydb`.`validite` (`idvalidite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_competences_cours_idx` ON `mydb`.`competences` (`cours_idcours` ASC) VISIBLE;

CREATE INDEX `fk_competences_validite1_idx` ON `mydb`.`competences` (`validite_idvalidite` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`eleve_has_professeur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`eleve_has_professeur` ;

CREATE TABLE IF NOT EXISTS `mydb`.`eleve_has_professeur` (
  `eleve_ideleve` INT NOT NULL,
  `professeur_idprofesseur` INT NOT NULL,
  PRIMARY KEY (`eleve_ideleve`, `professeur_idprofesseur`),
  CONSTRAINT `fk_eleve_has_professeur_eleve1`
    FOREIGN KEY (`eleve_ideleve`)
    REFERENCES `mydb`.`eleve` (`ideleve`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_eleve_has_professeur_professeur1`
    FOREIGN KEY (`professeur_idprofesseur`)
    REFERENCES `mydb`.`professeur` (`idprofesseur`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_eleve_has_professeur_professeur1_idx` ON `mydb`.`eleve_has_professeur` (`professeur_idprofesseur` ASC) VISIBLE;

CREATE INDEX `fk_eleve_has_professeur_eleve1_idx` ON `mydb`.`eleve_has_professeur` (`eleve_ideleve` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `mydb`.`competences_has_eleve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`competences_has_eleve` ;

CREATE TABLE IF NOT EXISTS `mydb`.`competences_has_eleve` (
  `competences_idcompetences` INT NOT NULL,
  `competences_cours_idcours` INT NOT NULL,
  `competences_validite_idvalidite` INT NOT NULL,
  `eleve_ideleve` INT NOT NULL,
  PRIMARY KEY (`competences_idcompetences`, `competences_cours_idcours`, `competences_validite_idvalidite`, `eleve_ideleve`),
  CONSTRAINT `fk_competences_has_eleve_competences1`
    FOREIGN KEY (`competences_idcompetences` , `competences_cours_idcours` , `competences_validite_idvalidite`)
    REFERENCES `mydb`.`competences` (`idcompetences` , `cours_idcours` , `validite_idvalidite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_competences_has_eleve_eleve1`
    FOREIGN KEY (`eleve_ideleve`)
    REFERENCES `mydb`.`eleve` (`ideleve`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_competences_has_eleve_eleve1_idx` ON `mydb`.`competences_has_eleve` (`eleve_ideleve` ASC) VISIBLE;

CREATE INDEX `fk_competences_has_eleve_competences1_idx` ON `mydb`.`competences_has_eleve` (`competences_idcompetences` ASC, `competences_cours_idcours` ASC, `competences_validite_idvalidite` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
