-- MySQL Script generated by MySQL Workbench
-- Thu Dec  3 16:15:53 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema id14922274_name
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema id14922274_name
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id14922274_name` DEFAULT CHARACTER SET utf8 ;
USE `id14922274_name` ;

-- -----------------------------------------------------
-- Table `id14922274_name`.`utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id14922274_name`.`utilisateur` ;

CREATE TABLE IF NOT EXISTS `id14922274_name`.`utilisateur` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomPrenom` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `motDePasse` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14922274_name`.`cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id14922274_name`.`cours` ;

CREATE TABLE IF NOT EXISTS `id14922274_name`.`cours` (
  `idcours` INT NOT NULL AUTO_INCREMENT,
  `nomCours` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idcours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14922274_name`.`competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id14922274_name`.`competences` ;

CREATE TABLE IF NOT EXISTS `id14922274_name`.`competences` (
  `idcompetences` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  `cours_idcours` INT NOT NULL,
  PRIMARY KEY (`idcompetences`, `cours_idcours`),
  INDEX `fk_competences_cours_idx` (`cours_idcours` ASC),
  CONSTRAINT `fk_competences_cours`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `id14922274_name`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14922274_name`.`utilisateur_has_cours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id14922274_name`.`utilisateur_has_cours` ;

CREATE TABLE IF NOT EXISTS `id14922274_name`.`utilisateur_has_cours` (
  `utilisateur_id` INT NOT NULL,
  `cours_idcours` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `cours_idcours`),
  INDEX `fk_utilisateur_has_cours_cours1_idx` (`cours_idcours` ASC),
  INDEX `fk_utilisateur_has_cours_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_utilisateur_has_cours_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `id14922274_name`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_cours_cours1`
    FOREIGN KEY (`cours_idcours`)
    REFERENCES `id14922274_name`.`cours` (`idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14922274_name`.`utilisateur_has_utilisateur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id14922274_name`.`utilisateur_has_utilisateur` ;

CREATE TABLE IF NOT EXISTS `id14922274_name`.`utilisateur_has_utilisateur` (
  `utilisateur_id` INT NOT NULL,
  `utilisateur_id1` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `utilisateur_id1`),
  INDEX `fk_utilisateur_has_utilisateur_utilisateur2_idx` (`utilisateur_id1` ASC),
  INDEX `fk_utilisateur_has_utilisateur_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_utilisateur_has_utilisateur_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `id14922274_name`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_utilisateur_utilisateur2`
    FOREIGN KEY (`utilisateur_id1`)
    REFERENCES `id14922274_name`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id14922274_name`.`utilisateur_has_competences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id14922274_name`.`utilisateur_has_competences` ;

CREATE TABLE IF NOT EXISTS `id14922274_name`.`utilisateur_has_competences` (
  `utilisateur_id` INT NOT NULL,
  `competences_idcompetences` INT NOT NULL,
  `competences_cours_idcours` INT NOT NULL,
  PRIMARY KEY (`utilisateur_id`, `competences_idcompetences`, `competences_cours_idcours`),
  INDEX `fk_utilisateur_has_competences_competences1_idx` (`competences_idcompetences` ASC, `competences_cours_idcours` ASC),
  INDEX `fk_utilisateur_has_competences_utilisateur1_idx` (`utilisateur_id` ASC),
  CONSTRAINT `fk_utilisateur_has_competences_utilisateur1`
    FOREIGN KEY (`utilisateur_id`)
    REFERENCES `id14922274_name`.`utilisateur` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_utilisateur_has_competences_competences1`
    FOREIGN KEY (`competences_idcompetences` , `competences_cours_idcours`)
    REFERENCES `id14922274_name`.`competences` (`idcompetences` , `cours_idcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
